---
name: Cargo Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        run: rustup install stable

      - name: Run cargo test
        run: cargo test
